server:
  port: 3344

spring:
  application:
    name:  cloud-config-center

  cloud:
    config:
      server:
        git:
          uri: https://github.com/1748983914/springcloud-config.git #GitHub上面的git仓库名字git@github.com:1748983914/springcloud-config.git
          search-paths:
            - springcloud-config
          #strict-host-key-checking: false
          username: 1748983914@qq.com
          password: liwei19980417...
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ # 入驻地址 集群版

#rabbitmq相关配置，暴露buss刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'