server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
    #互相注册，互相守望
  client:
    #false表示不想服务注册中心注册自己
    register-with-eureka: false
    #falese表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
      #设置与Euraka Server交互的地址查询服务和注册服务都需要依赖这个地址。
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  #server:
    #关闭自我保护机制，服务不可用及时剔除
   # enable-self-preservation: false
   # eviction-interval-timer-in-ms: 2000